//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: KLGWServer.proto
namespace KLGWServerMsg
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoginQueuingNtf")]
  public partial class LoginQueuingNtf : global::ProtoBuf.IExtensible
  {
    public LoginQueuingNtf() {}
    
    private uint _iBeforeCount;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"iBeforeCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint iBeforeCount
    {
      get { return _iBeforeCount; }
      set { _iBeforeCount = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoginConfigMD5Ntf")]
  public partial class LoginConfigMD5Ntf : global::ProtoBuf.IExtensible
  {
    public LoginConfigMD5Ntf() {}
    
    private string _strFileName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"strFileName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string strFileName
    {
      get { return _strFileName; }
      set { _strFileName = value; }
    }
    private ulong _bMD5Low;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"bMD5Low", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong bMD5Low
    {
      get { return _bMD5Low; }
      set { _bMD5Low = value; }
    }
    private ulong _bMD5High;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"bMD5High", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong bMD5High
    {
      get { return _bMD5High; }
      set { _bMD5High = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}