//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: KLoginClient.proto
namespace KLogin
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UDPLinkOpenReq")]
  public partial class UDPLinkOpenReq : global::ProtoBuf.IExtensible
  {
    public UDPLinkOpenReq() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UDPLinkCloseReq")]
  public partial class UDPLinkCloseReq : global::ProtoBuf.IExtensible
  {
    public UDPLinkCloseReq() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HeartBeatReq")]
  public partial class HeartBeatReq : global::ProtoBuf.IExtensible
  {
    public HeartBeatReq() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Login1Req")]
  public partial class Login1Req : global::ProtoBuf.IExtensible
  {
    public Login1Req() {}
    
    private ulong _arFakeParam = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"arFakeParam", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong arFakeParam
    {
      get { return _arFakeParam; }
      set { _arFakeParam = value; }
    }
    private int _iVersion;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"iVersion", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int iVersion
    {
      get { return _iVersion; }
      set { _iVersion = value; }
    }
    private KLogin.Login1Req.ClientVersion _sClientVersion;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"sClientVersion", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public KLogin.Login1Req.ClientVersion sClientVersion
    {
      get { return _sClientVersion; }
      set { _sClientVersion = value; }
    }
    private uint _proxyType = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"proxyType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint proxyType
    {
      get { return _proxyType; }
      set { _proxyType = value; }
    }
    private string _strToken;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"strToken", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string strToken
    {
      get { return _strToken; }
      set { _strToken = value; }
    }
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ClientVersion")]
  public partial class ClientVersion : global::ProtoBuf.IExtensible
  {
    public ClientVersion() {}
    
    private uint _branchVersion;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"branchVersion", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint branchVersion
    {
      get { return _branchVersion; }
      set { _branchVersion = value; }
    }
    private uint _branchChildVersion;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"branchChildVersion", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint branchChildVersion
    {
      get { return _branchChildVersion; }
      set { _branchChildVersion = value; }
    }
    private uint _hotfixVersion;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"hotfixVersion", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint hotfixVersion
    {
      get { return _hotfixVersion; }
      set { _hotfixVersion = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Login2Req")]
  public partial class Login2Req : global::ProtoBuf.IExtensible
  {
    public Login2Req() {}
    
    private ulong _arFakeParam = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"arFakeParam", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong arFakeParam
    {
      get { return _arFakeParam; }
      set { _arFakeParam = value; }
    }
    private int _iVersion;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"iVersion", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int iVersion
    {
      get { return _iVersion; }
      set { _iVersion = value; }
    }
    private KLogin.Login2Req.ClientVersion _sClientVersion;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"sClientVersion", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public KLogin.Login2Req.ClientVersion sClientVersion
    {
      get { return _sClientVersion; }
      set { _sClientVersion = value; }
    }
    private string _strToken;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"strToken", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string strToken
    {
      get { return _strToken; }
      set { _strToken = value; }
    }
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ClientVersion")]
  public partial class ClientVersion : global::ProtoBuf.IExtensible
  {
    public ClientVersion() {}
    
    private uint _branchVersion;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"branchVersion", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint branchVersion
    {
      get { return _branchVersion; }
      set { _branchVersion = value; }
    }
    private uint _branchChildVersion;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"branchChildVersion", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint branchChildVersion
    {
      get { return _branchChildVersion; }
      set { _branchChildVersion = value; }
    }
    private uint _hotfixVersion;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"hotfixVersion", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint hotfixVersion
    {
      get { return _hotfixVersion; }
      set { _hotfixVersion = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}